# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test self-hosted action runner

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: mikesay

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print readme
      run: cat README.md